### ISSUE TITLE
Transaction verification issue

### ISSUE THREAD

**Issue by femotizo** [yabacon/paystack-opencart#1]
@ibrahimlawal @Olumyco I Tested the Paystack module and noticed that after using the test card, the checkout page keep reloading without getting any response of the transaction and the payment was made. i checked the Contoller script and noticed the issue was transaction verification not getting the right response.

After spending a lot of time trying to find the cause, seems the PHP Curl Header wasn't set correctly. 

**i change** 

```
   curl_setopt(
            $ch, CURLOPT_HTTPHEADER, [
            "Authorization: Bearer " . $skey]
        );
```

**to**

```
curl_setopt(
           $ch, CURLOPT_HTTPHEADER, array(
             'Authorization: Bearer '.$skey // you can replace this with your $skey variable
         ));
```

 The same on github master Branch v1.5x & v2.x, Opencart extension [http://www.opencart.com/index.php?route=extension/extension/info&extension_id=25767&filter_search=paystack](url)

**Comment by ibrahimlawal** [comment]
Gee thanks!
