### ISSUE TITLE
Error with  Callback Redirect

### ISSUE THREAD

**Issue by nnanna217** [yabacon/paystack-opencart#3]
Hello,

Tried using the Opencart payment Module, but have issues with it as on payment it keeps redirecting to the checkout page instead of the success page.

Also tried doing this on AWS, and get an error 500 when it gets to the point of selecting payment method

**Comment by ibrahimlawal** [comment]
Hi @nnanna217, kindly provide a screenshot or test url for said checkout page. Mods are known to sometimes break functionality of plugins. Are you using any mods?

**Comment by nnanna217** [comment]
Hello,

Test url is www.doroswag.com. 
For the AWS server - http://52.37.172.163/teesbydarby/
The both use mods

**Comment by nnanna217** [comment]
I'm using VQ Mods.

Here is the error I got in the Errorl log of opencart

2016-06-25 17:08:55 - PAYSTACK :: CALLBACK DATA: Array
(
    [route] => payment/paystack/callback
    [trxref] => 26-576eba778fd00
)

**Comment by ibrahimlawal** [comment]
That's a false error. It's reporting the callback attempt as an error. The callback step calls that route and provides the trxref as a GET parameter.

**Comment by ibrahimlawal** [comment]
The Paystack controller will then verify the transaction with the Paystack API and update the status as required. Kindly share the VQ Mods code, perhaps we could look at what it expects for a successful transaction.

**Comment by nnanna217** [comment]
Here is the Vqmod.php code.(vqmod.com)
https://gist.github.com/nnanna217/7cf97cb9b37cd1c69192f62bea9460a2

But we tried this even before installing the VQmod and got same error. 
Would like to confirm if it tallies with the problem we fixed on stripe payment.
Do you have an Sql script having `Select order_id from DB_PREFIX.order` .... some where?

We hadn't used a `DB_Prefix` so the order table name clashed with an sql keyword. Which we had to escape with `order` manually. If so, were do we find this file to modify.

Maybe that could work

**Comment by nnanna217** [comment]
![paystack](https://cloud.githubusercontent.com/assets/1811905/16362045/848be0aa-3b9b-11e6-830e-c58d18d43ef5.JPG)

Just to confirm...The receipt does actually deliver to my email. The callback though doesn't get fired and so the Cart is not cleared, and doesnot successfully redirect

**Comment by ibrahimlawal** [comment]
Hey Nnanna, I attempted to make the same controller handle the callback and the index. Kindly update your `catalog/controller/payment/paystack.php` to this: https://github.com/ibrahimlawal/paystack-opencart/blob/vqmod-compat/2.x/upload/catalog/controller/payment/paystack.php so we may test again.

**Comment by ibrahimlawal** [comment]
> But we tried this even before installing the VQmod and got same error. 
> Would like to confirm if it tallies with the problem we fixed on stripe payment.
> Do you have an Sql script having Select order_id from DB_PREFIX.order .... some where?

That's all kinds of weird... Perhaps it's not the VQmod breaking the flow but something else... I don't use any SQL directly except for the geo zones .

**Comment by nnanna217** [comment]
Still the same thing. Error persists
This time, it showed nothing on the error log

**Comment by ibrahimlawal** [comment]
Kindly replace with this instead:  https://github.com/ibrahimlawal/paystack-opencart/blob/vqmod-2compat/2.x/upload/catalog/controller/payment/paystack.php

**Comment by nnanna217** [comment]
Thanks Ibrahim. Totally Worked.

What seemed to be the problem

**Comment by ibrahimlawal** [comment]
TLSv1.2 support is not available for your server's cURL and/or openSSL; But now I switched to `stream_create_context`, which has worked fine for you.
