### ISSUE TITLE
Paystack Payment Failed In testmode

### ISSUE THREAD

**Issue by othreecodes** [yabacon/paystack-opencart#5]
I am Using the Paystack plugin on my site http://straightgatepublishers.com/ (You can try it out too)
and everytime  I make a payment It says sucessfull but when I check the payment history it says payment failed. Plus no notification recieved.

Opencart v 2.3.2.2
Paystack-Opencart v2.3.x

**Comment by iC00kScripts** [comment]
solution to #3 might work.... do check it out

**Comment by ibrahimlawal** [comment]
@othreecodes that's most probably because of a failure to verify the transaction. Kindly confirm that your server can make a TLSv1.2 connection to our server

**Comment by ibrahimlawal** [comment]
@arashifunsho thanks! @othreecodes did that work?

**Comment by othreecodes** [comment]
@ibrahimlawal I tried that already. Didnt work.

**Comment by ibrahimlawal** [comment]
@othreecodes try updating your server PHP, cURL and OpenSSL. That's always gonna fix it.
